import { createCipheriv, createDecipheriv, createHmac, randomBytes, randomInt, scryptSync, timingSafeEqual } from "node:crypto";
const SECRET = process.env.JWT_SECRET || "dev-secret-cambia-esto-en-produccion";
const KEY = scryptSync(process.env.ENCRYPTION_KEY || SECRET, "generador-practica", 32);
const SETS = { lower: "abcdefghijkmnopqrstuvwxyz", upper: "ABCDEFGHJKLMNPQRSTUVWXYZ", numbers: "23456789", symbols: "!@#$%&*?" };
function b64url(input) { return Buffer.from(input).toString("base64").replaceAll("+", "-").replaceAll("/", "_").replaceAll("=", ""); }
function fromB64url(input) { const padded = input.replaceAll("-", "+").replaceAll("_", "/") + "===".slice((input.length + 3) % 4); return Buffer.from(padded, "base64").toString("utf8"); }
export function hashPassword(password) { const salt = randomBytes(16).toString("hex"); return `${salt}:${scryptSync(password, salt, 32).toString("hex")}`; }
export function verifyPassword(password, stored) { const [salt, hash] = String(stored).split(":"); if (!salt || !hash) return false; const next = scryptSync(password, salt, 32); const prev = Buffer.from(hash, "hex"); return prev.length === next.length && timingSafeEqual(prev, next); }
export function signToken(user, expiresInSec = 60 * 60 * 24 * 7) { const header = b64url(JSON.stringify({ alg: "HS256", typ: "JWT" })); const payload = b64url(JSON.stringify({ id: user.id, username: user.username, exp: Math.floor(Date.now() / 1000) + expiresInSec })); const data = `${header}.${payload}`; return `${data}.${createHmac("sha256", SECRET).update(data).digest("base64url")}`; }
export function verifyToken(token) { const parts = String(token || "").split("."); if (parts.length !== 3) return null; const [header, payload, sig] = parts; const expected = createHmac("sha256", SECRET).update(`${header}.${payload}`).digest("base64url"); const a = Buffer.from(sig); const b = Buffer.from(expected); if (a.length !== b.length || !timingSafeEqual(a, b)) return null; try { const data = JSON.parse(fromB64url(payload)); if (!data.exp || data.exp < Math.floor(Date.now() / 1000)) return null; return data; } catch { return null; } }
export function getUserFromRequest(req) { const header = req.headers.authorization || ""; return verifyToken(header.startsWith("Bearer ") ? header.slice(7) : ""); }
export function encrypt(text) { const iv = randomBytes(12); const cipher = createCipheriv("aes-256-gcm", KEY, iv); const data = Buffer.concat([cipher.update(String(text), "utf8"), cipher.final()]); return `${iv.toString("base64url")}.${cipher.getAuthTag().toString("base64url")}.${data.toString("base64url")}`; }
export function decrypt(payload) { const [iv, tag, data] = String(payload || "").split("."); const decipher = createDecipheriv("aes-256-gcm", KEY, Buffer.from(iv, "base64url")); decipher.setAuthTag(Buffer.from(tag, "base64url")); return Buffer.concat([decipher.update(Buffer.from(data, "base64url")), decipher.final()]).toString("utf8"); }
export function generatePassword(length, flags) { const pools = Object.entries(SETS).filter(([name]) => flags[name] !== false).map(([, chars]) => chars); const alphabet = pools.join("") || SETS.lower; const size = Math.max(8, Math.min(32, Number(length) || 16)); const chars = pools.map((pool) => pool[randomInt(pool.length)]); while (chars.length < size) chars.push(alphabet[randomInt(alphabet.length)]); for (let i = chars.length - 1; i > 0; i -= 1) { const j = randomInt(i + 1); [chars[i], chars[j]] = [chars[j], chars[i]]; } return chars.join(""); }
